export const products = [
  {
    id: 1,
    name: 'Mineralfutter',
    manufacturer: 'VILOFOSS',
    description: 'Премікси для ВРХ, ДРХ та Коней',
    category: ['ВРХ дорослі', 'ВРХ молодняк', 'ДРХ', 'Коні'],
  },
  {
    id: 2,
    name: 'LM Rinder ADE',
    manufacturer: 'VILOFOSS',
    description: 'Премікс - лизунець Стандарт',
    category: ['ВРХ дорослі', 'ВРХ молодняк', 'ДРХ', 'Коні'],
  },
  {
    id: 3,
    name: 'LM Rinder TR-Vit',
    manufacturer: 'VILOFOSS',
    description: 'Лизунець для сухостійних корів',
    category: ['ВРХ дорослі', 'ВРХ молодняк'],
  },
  {
    id: 4,
    name: 'Камінь для клювання',
    manufacturer: 'VILOFOSS',
    description: 'Матеріал для птахівників',
    category: 'Птиця'
  },
  {
    id: 5,
    name: 'ProtiSpar Top 75',
    manufacturer: 'VILOFOSS',
    description: 'Оптимізація протеїнової годівлі',
    category: ['ВРХ дорослі', 'ВРХ молодняк', 'ДРХ', 'Коні'],
  },
  {
    id: 6,
    name: 'Футтергут Румі-Ферм',
    manufacturer: 'VILOFOSS',
    description: 'Оптимізація крохмальної годівлі',
    category: ['ВРХ дорослі'],
  },
  {
    id: 7,
    name: 'Lactoval liquid',
    manufacturer: 'VILOFOSS',
    description: 'Перша випойка після отелу',
    category: ['ВРХ дорослі', 'ВРХ молодняк'],
  },
  {
    id: 8,
    name: 'X-Zelit Calcium-Mobilisation',
    manufacturer: 'VILOFOSS',
    description: 'Профілактика гіпокальціємії',
    category: ['ВРХ дорослі'],
  },
  {
    id: 9,
    name: 'Br. Close Up 30 Pro',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Транзитна добавка для корів',
    category: ['ВРХ дорослі'],
  },
  {
    id: 10,
    name: 'Clex® blue drink',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: `Рідкий мінерально–вітамінний
    підкислювач (підходе для всіх)`,
    category: ['Підходе для всіх'],
  },
  {
    id: 11,
    name: 'Clex® Beta-Inulin met BLUE',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: `Імуностимулююча кормова
    добавка  (підходе для всіх)`,
    category: ['Підходе для всіх'],
  },
  {
    id: 12,
    name: 'Quattro drink',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Рідкий підкислювач для всіх видів тварин',
    category: ['ВРХ молодняк', 'ДРХ', 'Свині', 'Птиця'],
  },
  {
    id: 13,
    name: 'Clex Vit Hefe 4',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Премікс+сорбент токсинів',
    category: ['Підходе для всіх'],
  },
  {
    id: 14,
    name: 'Anta®Ferm MT80',
    manufacturer: 'VILOFOSS',
    description: 'Сорбент токсинів комплексний',
    category: ['Підходе для всіх'],
  },
  {
    id: 15,
    name: 'SuperSorber Mykotoxinbinder',
    manufacturer: 'VILOFOSS',
    description: 'Сорбент токсинів',
    category: ['Підходе для всіх'],
  },
  {
    id: 16,
    name: 'Pansen-Neutral',
    manufacturer: 'VILOFOSS',
    description: 'Буферна кормова добавка',
    category: ['ВРХ дорослі'],
  },
  {
    id: 17,
    name: 'Acid-Control',
    manufacturer: 'VILOFOSS',
    description: 'Буферна кормова добавка',
    category: ['ВРХ дорослі'],
  },
  {
    id: 18,
    name: 'Biotin 750',
    manufacturer: 'VILOFOSS',
    description: 'Концентрат Біотину',
    category: ['ВРХ дорослі'],
  },
  {
    id: 19,
    name: 'Beta-Carotin',
    manufacturer: 'VILOFOSS',
    description: 'Концентрат каротину',
    category: ['ВРХ дорослі'],
  },
  {
    id: 20,
    name: 'Kuhpower',
    manufacturer: 'VILOFOSS',
    description: 'Спеціальна дріжджова добавка',
    category: ['ВРХ дорослі'],
  },
  {
    id: 21,
    name: 'Elbe Trockenfett DF',
    manufacturer: 'VILOFOSS',
    description: 'Фракціонований захищений жир',
    category: ['ВРХ дорослі'],
  },
  {
    id: 22,
    name: 'Профат',
    manufacturer: 'Schils',
    description: 'Кальцінований захищений жир',
    category: ['ВРХ дорослі'],
  },
  {
    id: 23,
    name: 'Propylenglycol',
    manufacturer: 'VILOFOSS',
    description: 'Енергетична рідка добавка',
    category: ['ВРХ дорослі'],
  },
  {
    id: 24,
    name: 'Glycerine 80%',
    manufacturer: 'VILOFOSS',
    description: 'Енергетична рідка добавка',
    category: ['ВРХ дорослі'],
  },
];

export function addNewEvent(newEvent) {
  products.push(newEvent);
}