export const products = [
  {
    id: 1,
    name: 'Mineralfutter',
    manufacturer: 'VILOFOSS',
    description: 'Премікси для ВРХ, ДРХ та Коней',
    category: ['ВРХ дорослі', 'ВРХ молодняк', 'ДРХ', 'Коні'],
  },
  {
    id: 2,
    name: 'LM Rinder ADE',
    manufacturer: 'VILOFOSS',
    description: 'Премікс - лизунець Стандарт',
    category: ['ВРХ дорослі', 'ВРХ молодняк', 'ДРХ', 'Коні'],
  },
  {
    id: 3,
    name: 'LM Rinder TR-Vit',
    manufacturer: 'VILOFOSS',
    description: 'Лизунець для сухостійних корів',
    category: ['ВРХ дорослі', 'ВРХ молодняк'],
  },
  {
    id: 4,
    name: 'Камінь для клювання',
    manufacturer: 'VILOFOSS',
    description: 'Матеріал для птахівників',
    category: [ 'Птиця' ],
  },
  {
    id: 5,
    name: 'ProtiSpar Top 75',
    manufacturer: 'VILOFOSS',
    description: 'Оптимізація протеїнової годівлі',
    category: ['ВРХ дорослі', 'ВРХ молодняк', 'ДРХ', 'Коні'],
  },
  {
    id: 6,
    name: 'Футтергут Румі-Ферм',
    manufacturer: 'VILOFOSS',
    description: 'Оптимізація крохмальної годівлі',
    category: ['ВРХ дорослі'],
  },
  {
    id: 7,
    name: 'Lactoval liquid',
    manufacturer: 'VILOFOSS',
    description: 'Перша випойка після отелу',
    category: ['ВРХ дорослі', 'ВРХ молодняк'],
  },
  {
    id: 8,
    name: 'X-Zelit Calcium-Mobilisation',
    manufacturer: 'VILOFOSS',
    description: 'Профілактика гіпокальціємії',
    category: ['ВРХ дорослі'],
  },
  {
    id: 9,
    name: 'Br. Close Up 30 Pro',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Транзитна добавка для корів',
    category: ['ВРХ дорослі'],
  },
  {
    id: 10,
    name: 'Clex® blue drink',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: `Рідкий мінерально–вітамінний підкислювач (підходе для всіх)`,
    category: ['Підходе для всіх'],
  },
  {
    id: 11,
    name: 'Clex® Beta-Inulin met BLUE',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: `Імуностимулююча кормова добавка  (підходе для всіх)`,
    category: ['Підходе для всіх'],
  },
  {
    id: 12,
    name: 'Quattro drink',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Рідкий підкислювач для всіх видів тварин',
    category: ['ВРХ молодняк', 'ДРХ', 'Свині', 'Птиця'],
  },
  {
    id: 13,
    name: 'Clex Vit Hefe 4',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Премікс+сорбент токсинів',
    category: ['Підходе для всіх'],
  },
  {
    id: 14,
    name: 'Anta®Ferm MT80',
    manufacturer: 'VILOFOSS',
    description: 'Сорбент токсинів комплексний',
    category: ['Підходе для всіх'],
  },
  {
    id: 15,
    name: 'SuperSorber Mykotoxinbinder',
    manufacturer: 'VILOFOSS',
    description: 'Сорбент токсинів',
    category: ['Підходе для всіх'],
  },
  {
    id: 16,
    name: 'Pansen-Neutral',
    manufacturer: 'VILOFOSS',
    description: 'Буферна кормова добавка',
    category: ['ВРХ дорослі'],
  },
  {
    id: 17,
    name: 'Acid-Control',
    manufacturer: 'VILOFOSS',
    description: 'Буферна кормова добавка',
    category: ['ВРХ дорослі'],
  },
  {
    id: 18,
    name: 'Biotin 750',
    manufacturer: 'VILOFOSS',
    description: 'Концентрат Біотину',
    category: ['ВРХ дорослі'],
  },
  {
    id: 19,
    name: 'Beta-Carotin',
    manufacturer: 'VILOFOSS',
    description: 'Концентрат каротину',
    category: ['ВРХ дорослі'],
  },
  {
    id: 20,
    name: 'Kuhpower',
    manufacturer: 'VILOFOSS',
    description: 'Спеціальна дріжджова добавка',
    category: ['ВРХ дорослі'],
  },
  {
    id: 21,
    name: 'Elbe Trockenfett DF',
    manufacturer: 'VILOFOSS',
    description: 'Фракціонований захищений жир',
    category: ['ВРХ дорослі'],
  },
  {
    id: 22,
    name: 'Профат',
    manufacturer: 'Schils',
    description: 'Кальцінований захищений жир',
    category: ['ВРХ дорослі'],
  },
  {
    id: 23,
    name: 'Propylenglycol',
    manufacturer: 'VILOFOSS',
    description: 'Енергетична рідка добавка',
    category: ['ВРХ дорослі'],
  },
  {
    id: 24,
    name: 'Glycerine 80%',
    manufacturer: 'VILOFOSS',
    description: 'Енергетична рідка добавка',
    category: ['ВРХ дорослі'],
  },
  {
    id: 25,
    name: 'VitaloMix',
    manufacturer: 'VILOFOSS',
    description: 'Престартер у вигляді мюсли',
    category: ['ВРХ молодняк'],
  },
  {
    id: 26,
    name: 'Ruminito TMR',
    manufacturer: 'VILOFOSS',
    description: '10% ядро для кормів телятам',
    category: ['ВРХ молодняк'],
  },
  {
    id: 27,
    name: 'Vollmilch plus',
    manufacturer: 'VILOFOSS',
    description: 'Збагачувач незбираного молока',
    category: ['ВРХ молодняк'],
  },
  {
    id: 28,
    name: 'Євролак (зелений)',
    manufacturer: 'Schils',
    description: 'ЗНМ для телят з 3-ї доби життя',
    category: ['ВРХ молодняк'],
  },
  {
    id: 29,
    name: 'RoCoSal E',
    manufacturer: 'VILOFOSS',
    description: 'Профілактика діареї у телят',
    category: ['ВРХ молодняк'],
  },
  {
    id: 30,
    name: 'Dialyt Express',
    manufacturer: 'VILOFOSS',
    description: 'Швидке лікування діареї у телят',
    category: ['ВРХ молодняк', 'ДРХ', 'Коні'],
  },
  {
    id: 31,
    name: 'RespoSan',
    manufacturer: 'VILOFOSS',
    description: 'Профілактика респіраторних хвороб у телят',
    category: ['ВРХ молодняк'],
  },
  {
    id: 32,
    name: 'ProbioBona',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Рідкий пероральний пробіотик в шприці',
    category: ['Підходе для всіх'],
  },
  {
    id: 33,
    name: 'Marathon Top',
    manufacturer: 'VILOFOSS',
    description: 'Спеціальний Премікс',
    category: ['ВРХ дорослі', 'ВРХ молодняк'],
  },
  {
    id: 34,
    name: 'Stalosan F',
    manufacturer: 'VILOFOSS',
    description: 'Дезинфектант в присутності тварин',
    category: ['Підходе для всіх'],
  },
  {
    id: 35,
    name: 'БІО-СИЛ',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Інокулянт для силосування',
    category: ['ВРХ дорослі'],
  },
  {
    id: 36,
    name: 'Sweet-Min Schafe',
    manufacturer: 'VILOFOSS',
    description: 'Лизунець меласований для овець',
    category: ['ДРХ'],
  },
  {
    id: 37,
    name: 'FUTTERGUT™',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Кормові концентрати та премікси для свиней, птиці, ВРХ',
    category: ['Підходе для всіх'],
  },
  {
    id: 38,
    name: 'Престартер для телят',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Престартер для телят. Гранула.',
     category: ['ВРХ молодняк'],
  },
  {
    id: 39,
    name: 'БМВД (універсальний)',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'БМВД. Гранула.',
    category: ['ВРХ дорослі', 'ВРХ молодняк', 'ДРХ', 'Коні'],
  },
  {
    id: 40,
    name: 'БМВД для корів',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Для лактуючих корів.',
    category: ['ВРХ дорослі'],
  },
  {
    id: 41,
    name: 'Гранула для корів',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Годівля на роботах',
    category: ['ВРХ дорослі'],
  },
  {
    id: 42,
    name: 'Премікс для дійних корів 1%',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Премікс з/без живими дріжджами',
    category: ['ВРХ дорослі'],
  },
  {
    id: 43,
    name: 'Футтергут-Лєвуселл для ВРХ',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Добавка з живими дріжджами',
    category: ['ВРХ дорослі'],
  },
  {
    id: 44,
    name: 'Премікс для дійних корів 3%',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Вітаміно-мінеральний Премікс',
    category: ['ВРХ дорослі'],
  },
  {
    id: 45,
    name: 'Премікс для сухостійних корів',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Премікс для сухостійних корів',
    category: ['ВРХ дорослі'],
  },
  {
    id: 46,
    name: 'AnkonaF/buffer/150',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Буферна добавка',
    category: ['ВРХ дорослі'],
  },
  {
    id: 47,
    name: 'Futtergut Hy-М',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Регулює кальцій-фосфорний метаболізм + іммунітет',
    category: ['Свині'],
  },
  {
    id: 48,
    name: 'NutriBos N 85 і NutriBos N 65',
    manufacturer: 'NUTRIBOS',
    description: 'Захищена сечовина (Хорватія)',
    category: ['ВРХ дорослі', 'ДРХ'],
  },
  {
    id: 49,
    name: 'NutriBos VN 75 і COMPLETE',
    manufacturer: 'NUTRIBOS',
    description: 'Комплексні продукти с захищеною сечовиною у складі (Хорватія)',
    category: ['ВРХ дорослі'],
  },
  {
    id: 50,
    name: 'SEGAWEAN® Boost',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Премікс для свиней на відгодівлі 30-60 кг, 4,5%',
    category: ['Свині'],
  },
  {
    id: 51,
    name: 'SEGAWEAN® F49 A3',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Премікс для свиней на відгодівлі від 60 кг, 3,3%',
    category: ['Свині'],
  },
  {
    id: 52,
    name: 'SOW Day 7® Farrow Feed',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Премікс для свиноматок у транзитний період',
    category: ['Свині'],
  },
  {
    id: 53,
    name: 'SEGAWEAN® SL Wean',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Премікс для лактуючих свиноматок, 5%',
    category: ['Свині'],
  },
  {
    id: 54,
    name: 'SEGAWEAN® SFT',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Премікс для супоросних свиноматок, 3%',
    category: ['Свині'],
  },
  {
    id: 55,
    name: 'SEGAWEAN® P5 +2 3 6',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Премікс для поросят до 30 кг 6,5%',
    category: ['Свині'],
  },
  {
    id: 56,
    name: 'Maxi-Cox Dry для птиці',
    manufacturer: 'ETOS',
    description: 'Модулятор мікробіому; Кокцидіостатик; Суміш органічних кислот',
    category: ['Птиця'],
  },
  {
    id: 57,
    name: 'Maxi-Pi-Blok Dry - для свиней',
    manufacturer: 'ETOS',
    description: 'Модулятор мікробіому; Альтернатива антибіотику; Суміш органічних кислот',
    category: ['Свині'],
  },
  {
    id: 58,
    name: 'Hy-M для свиней',
    manufacturer: ['ANKONA', 'FUTTERGUT - надійна годівля'],
    description: 'Модулятор мікробіому; Альтернатива антибіотику; Суміш органічних кислот',
    category: ['Свині'],
  },
  {
    id: 59,
    name: 'Hy-M для батьківського стада птиці',
    manufacturer: ['ANKONA', 'FUTTERGUT - надійна годівля'],
    description: 'Підвищення рівня вітаміну D3 у сироватці крові',
    category: ['Птиця'],
  },
  {
    id: 60,
    name: 'Hy-M для бройлерів',
    manufacturer: ['ANKONA', 'FUTTERGUT - надійна годівля'],
    description: 'Підвищення рівня вітаміну D3 у сироватці крові',
    category: ['Птиця'],
  },
  {
    id: 61,
    name: 'Hy-M для несучки',
    manufacturer: ['ANKONA', 'FUTTERGUT - надійна годівля'],
    description: 'Підвищення рівня вітаміну D3 у сироватці крові',
    category: ['Птиця'],
  },
  {
    id: 62,
    name: 'Мультіцид Форте',
    manufacturer: ['ETOS'],
    description: 'Додаткова кормова суміш',
    category: ['Підходе для всіх'],
  },
  {
    id: 63,
    name: 'Цітро',
    manufacturer: ['Agro-Bizek'],
    description: 'Ультрабіотик',
    category: ['Підходе для всіх'],
  },
  {
    id: 64,
    name: 'Арбоцель',
    manufacturer: ['JRS'],
    description: 'Концентрат сирої клітковини для свиней',
    category: ['Свині'],
  },
];

export function addNewEvent(newEvent) {
  products.push(newEvent);
}