export const products = [
  {
    id: 1,
    name: 'Mineralfutter',
    category: ['Коні', 'ВРХ дорослі'],
    manufacturer: 'VILOFOSS',
    description: 'Премікси для ВРХ, ДРХ та Коней',
  },
  { id: 2, name: 'Feed Mix', category: 'ДРХ', manufacturer: 'JRS' },
  {
    id: 3,
    name: 'SuperFeed',
    category: 'ВРХ дорослі',
    manufacturer: 'FUTTERGUT — надійна годівля',
  },
  { id: 4, name: 'SuperFeed', category: 'Свині', manufacturer: 'ETOS' },
  { id: 5, name: 'Feed Mix', category: 'ДРХ', manufacturer: 'JRS' },
  {
    id: 6,
    name: 'Mineralfluter',
    category: 'ВРХ молодняк',
    manufacturer: 'AGRO-BIZEK',
  },
  {
    id: 7,
    name: 'Mineralfluter',
    category: 'Підходе для всіх',
    manufacturer: 'Anhoff FUTTERGUT',
  },
  { id: 8, name: 'Feed Mix', category: 'ДРХ', manufacturer: 'JRS' },
  { id: 9, name: 'SuperFeed', category: 'ВРХ дорослі', manufacturer: 'ETOS' },
  {
    id: 10,
    name: 'SuperFeed',
    category: 'Свині',
    manufacturer: 'FUTTERGUT — надійна годівля',
  },
  { id: 11, name: 'Feed Mix', category: 'ДРХ', manufacturer: 'JRS' },
  {
    id: 12,
    name: 'Mineralfluter',
    category: 'Підходе для всіх',
    manufacturer: 'Anhoff FUTTERGUT',
  },
  {
    id: 13,
    name: 'Mineralfluter',
    category: 'Коні',
    manufacturer: 'AGRO-BIZEK',
  },
  { id: 14, name: 'Feed Mix', category: 'ДРХ', manufacturer: 'JRS' },
  {
    id: 15,
    name: 'SuperFeed',
    category: 'Підходе для всіх',
    manufacturer: 'FUTTERGUT — надійна годівля',
  },
  { id: 16, name: 'SuperFeed', category: 'Свині', manufacturer: 'ETOS' },
  { id: 17, name: 'Feed Mix', category: 'ДРХ', manufacturer: 'JRS' },
  {
    id: 18,
    name: 'Mineralfluter',
    category: 'ВРХ молодняк',
    manufacturer: 'AGRO-BIZEK',
  },
  {
    id: 19,
    name: 'Mineralfluter',
    category: 'Підходе для всіх',
    manufacturer: 'Anhoff FUTTERGUT',
  },
  { id: 20, name: 'Feed Mix', category: 'ДРХ', manufacturer: 'JRS' },
  { id: 21, name: 'SuperFeed', category: 'ВРХ дорослі', manufacturer: 'ETOS' },
  {
    id: 22,
    name: 'SuperFeed',
    category: 'Підходе для всіх',
    manufacturer: 'FUTTERGUT — надійна годівля',
  },
  {
    id: 23,
    name: 'Mineralfluter',
    category: 'Коні',
    manufacturer: 'Anhoff FUTTERGUT',
  },
  {
    id: 24,
    name: 'Mineralfluter',
    category: 'Коні',
    manufacturer: 'AGRO-BIZEK',
  },
  { id: 25, name: 'Feed Mix', category: 'ДРХ', manufacturer: 'JRS' },
  {
    id: 26,
    name: 'SuperFeed',
    category: 'ВРХ дорослі',
    manufacturer: 'FUTTERGUT — надійна годівля',
  },
  { id: 27, name: 'SuperFeed', category: 'Свині', manufacturer: 'ETOS' },
  { id: 28, name: 'Feed Mix', category: 'ДРХ', manufacturer: 'JRS' },
  {
    id: 29,
    name: 'Mineralfluter',
    category: 'ВРХ молодняк',
    manufacturer: 'AGRO-BIZEK',
  },
  {
    id: 30,
    name: 'Mineralfluter',
    category: 'Підходе для всіх',
    manufacturer: 'Anhoff FUTTERGUT',
  },
  { id: 31, name: 'Feed Mix', category: 'ДРХ', manufacturer: 'JRS' },
  { id: 32, name: 'SuperFeed', category: 'ВРХ дорослі', manufacturer: 'ETOS' },
  {
    id: 33,
    name: 'SuperFeed',
    category: 'Свині',
    manufacturer: 'FUTTERGUT — надійна годівля',
  },
  { id: 34, name: 'Feed Mix', category: 'ДРХ', manufacturer: 'JRS' },
  {
    id: 35,
    name: 'Mineralfluter',
    category: 'Підходе для всіх',
    manufacturer: 'Anhoff FUTTERGUT',
  },
  {
    id: 36,
    name: 'Mineralfluter',
    category: 'Коні',
    manufacturer: 'AGRO-BIZEK',
  },
  { id: 37, name: 'Feed Mix', category: 'ДРХ', manufacturer: 'JRS' },
  {
    id: 38,
    name: 'SuperFeed',
    category: 'Підходе для всіх',
    manufacturer: 'FUTTERGUT — надійна годівля',
  },
  { id: 39, name: 'SuperFeed', category: 'Свині', manufacturer: 'ETOS' },
  { id: 40, name: 'Feed Mix', category: 'ДРХ', manufacturer: 'JRS' },
  {
    id: 41,
    name: 'Mineralfluter',
    category: 'ВРХ молодняк',
    manufacturer: 'AGRO-BIZEK',
  },
  {
    id: 42,
    name: 'Mineralfluter',
    category: 'Підходе для всіх',
    manufacturer: 'Anhoff FUTTERGUT',
  },
  { id: 43, name: 'Feed Mix', category: 'ДРХ', manufacturer: 'JRS' },
  { id: 44, name: 'SuperFeed', category: 'ВРХ дорослі', manufacturer: 'ETOS' },
  {
    id: 45,
    name: 'SuperFeed',
    category: 'Підходе для всіх',
    manufacturer: 'FUTTERGUT — надійна годівля',
  },
  { id: 46, name: 'Feed Mix', category: 'ДРХ', manufacturer: 'JRS' },
  {
    id: 47,
    name: 'Mineralfluter',
    category: 'Коні',
    manufacturer: 'Anhoff FUTTERGUT',
  },
];

export function addNewEvent(newEvent) {
  products.push(newEvent);
}