import imgProductDetails1 from 'images/productDetails/imgProductDetailsId1.jpg';

export const products = [
  {
    id: 1,
    name: 'Mineralfutter',
    manufacturer: 'VILOFOSS',
    description: 'Премікси для ВРХ, ДРХ та Коней',
    category: ['ВРХ дорослі', 'ВРХ молодняк', 'ДРХ', 'Коні'],
    image: imgProductDetails1,
    sections: [
      {
        title: 'Можуть бути представлені:',
        items: ['стандартна лінійка', 'індивідуальні рецептури'],
      },
      {
        title: 'Дозування:',
        items: ['50-250 г/гол/добу (залежить від рецептури)'],
      },
      {
        title: 'Фасування:',
        items: ['мішок 25 кг'],
      },
    ],
  },
  {
    id: 2,
    name: 'LM Rinder ADE',
    manufacturer: 'VILOFOSS',
    description: 'Смачний та гомогенний лизунець',
    category: ['ВРХ дорослі', 'ВРХ молодняк', 'ДРХ', 'Коні'],
    image: imgProductDetails1,
    sections: [
      {
        title: 'Складові:',
        items: [
          'Са 15,0%, Р 4,0%, Na 2,9%, Mg 5,0% - віт.А 800 000 МЕ, віт.D 130 000 МЕ, віт. Е 2000 мг, залізо 1000 мг, мідь 800мг, марганец 4000мг, цинк 6000мг, йод 50мг, селен 50мг, кобальт 30мг.',
        ],
      },
      {
        title: 'Середня норма вживання:',
        items: ['100-200 г/гол/добу'],
      },
      {
        title: 'Рекомендовано:',
        items: [
          'молодняку ВРХ - при відлученні від молока й за 1-2 міс до початку парувальної кампанії',
          'сухостійним коровам - на весь термін сухостою',
          'лактуючим коровам - від отелу до 100 днів лактації',
        ],
      },
      {
        title: 'Фасування:',
        items: ['таз 25 та 65 кг'],
      },
    ],
  },
  {
    id: 3,
    name: 'LM Rinder TR-Vit',
    manufacturer: 'VILOFOSS',
    description: 'Лизунець для сухостійних корів',
    category: ['ВРХ дорослі', 'ВРХ молодняк'],
    image: imgProductDetails1,
    sections: [
      {
        title: 'Використання лизунців для сухостійних корів сприяє:',
        items: ['скорішому відновленню корови після отелу', 'підтримує роботу імунної систему корови', 'правильний розвиток майбутнього теляти', 'знижує ризик порушень обміну речовин', 'покращує якість молозива - захист телят', 'підтримує високий рівень надою після отелу'],
      },
      {
        title: 'Починати використання продукту:',
        items: ['за 8 - 12 тижнів до отелу, або на весь термін сухостою!']
      },
      {
        title: 'Складові:',
        items: ['Са 5,0%, Р 5,0%, Na 16,0%, Mg 8,0%, віт. А 500 000 МЕ, віт.D 50 000 МЕ, віт.Е 2000 мг, мідь 800 мг, марганець 4000 мг, цинк 6000 мг, йод 50 мг, селен 50 мг, кобальт 30 мг']
      },
      {
        title: 'Середня норма вживання:',
        items: ['100-200 г/гол/добу']
      },
      {
        title: 'Фасування:',
        items: ['таз 65 кг']
      },
    ]
  },
  {
    id: 4,
    name: 'Камінь для клювання',
    manufacturer: 'VILOFOSS',
    description: 'Професійний матеріал для птахівників',
    category: ['Птиця'],
    image: imgProductDetails1,
    sections: [
      {
        title: 'Складові:',
        items: ['індивідуальне введення життєво важливих мінералів, таких як: магній, кальцій та натрій'],
      },
      {
        title: 'Мета використання:',
        items: ['щоб уникнути поведінкових розладів, таких як, клювання пір’я та канібалізм, що призводять до серйозних наслідків та втрат, покращення перетравності кормів'],
      },
      {
        title: 'Дозування:',
        items: ['рекомендуємо використовувати один камінь Peckstone для кожних 500 - 800 несучок та індичок, або на кожні 1000 бройлерів'],
      },
      {
        title: 'Фасування:',
        items: ['камінь для клювання по 10 кг'],
      },
    ]
  },
  {
    id: 5,
    name: 'ProtiSpar Top 75',
    manufacturer: 'VILOFOSS',
    description: 'Оптимізація протеїнової годівлі',
    descriptionText: 'Запатентована комбинація деяких ефірних олій: знижує швидке виділення амміаку з амінокислот, без погіршення синтезу оцтової й пропіонової кислот, тому не має негативного впливу на виробництво молока та молочного жиру.',
    category: ['ВРХ дорослі', 'ВРХ молодняк', 'ДРХ', 'Коні'],
    image: imgProductDetails1,
    sections: [
      {
        title: 'Переваги:',
        items: ['оптимізує витрати на протеїнову годівлю', 'знижує нагрузку від аміаку на печінку', 'більше протеину потрапляє до тонкого кишківника', 'розвантажує систему енергетичного обміну', 'підтримка здоров’я й відтворної здатності', 'оптимізує економічну ефективність виробництва молока'],
      },
      {
        title: 'Дозування:',
        items: ['75 г/гол/добу']
      },
      {
        title: 'Фасування:',
        items: ['мішок 25 кг']
      },
    ]
  },
  {
    id: 6,
    name: 'Футтергут Румі-Ферм',
    manufacturer: 'VILOFOSS',
    description: 'Оптимізація крохмальної годівлі',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 7,
    name: 'Lactoval liquid',
    manufacturer: 'VILOFOSS',
    description: 'Перша випойка після отелу',
    category: ['ВРХ дорослі', 'ВРХ молодняк'],
    image: imgProductDetails1,
  },
  {
    id: 8,
    name: 'X-Zelit Calcium-Mobilisation',
    manufacturer: 'VILOFOSS',
    description: 'Профілактика гіпокальціємії',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 9,
    name: 'Br. Close Up 30 Pro',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Транзитна добавка для корів',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 10,
    name: 'Clex® blue drink',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: `Рідкий мінерально–вітамінний підкислювач (підходе для всіх)`,
    category: ['Підходе для всіх'],
    image: imgProductDetails1,
  },
  {
    id: 11,
    name: 'Clex® Beta-Inulin met BLUE',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: `Імуностимулююча кормова добавка  (підходе для всіх)`,
    category: ['Підходе для всіх'],
    image: imgProductDetails1,
  },
  {
    id: 12,
    name: 'Quattro drink',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Рідкий підкислювач для всіх видів тварин',
    category: ['ВРХ молодняк', 'ДРХ', 'Свині', 'Птиця'],
    image: imgProductDetails1,
  },
  {
    id: 13,
    name: 'Clex Vit Hefe 4',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Премікс+сорбент токсинів',
    category: ['Підходе для всіх'],
    image: imgProductDetails1,
  },
  {
    id: 14,
    name: 'Anta®Ferm MT80',
    manufacturer: 'VILOFOSS',
    description: 'Сорбент токсинів комплексний',
    category: ['Підходе для всіх'],
    image: imgProductDetails1,
  },
  {
    id: 15,
    name: 'SuperSorber Mykotoxinbinder',
    manufacturer: 'VILOFOSS',
    description: 'Сорбент токсинів',
    category: ['Підходе для всіх'],
    image: imgProductDetails1,
  },
  {
    id: 16,
    name: 'Pansen-Neutral',
    manufacturer: 'VILOFOSS',
    description: 'Буферна кормова добавка',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 17,
    name: 'Acid-Control',
    manufacturer: 'VILOFOSS',
    description: 'Буферна кормова добавка',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 18,
    name: 'Biotin 750',
    manufacturer: 'VILOFOSS',
    description: 'Концентрат Біотину',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 19,
    name: 'Beta-Carotin',
    manufacturer: 'VILOFOSS',
    description: 'Концентрат каротину',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 20,
    name: 'Kuhpower',
    manufacturer: 'VILOFOSS',
    description: 'Спеціальна дріжджова добавка',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 21,
    name: 'Elbe Trockenfett DF',
    manufacturer: 'VILOFOSS',
    description: 'Фракціонований захищений жир',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 22,
    name: 'Профат',
    manufacturer: 'Schils',
    description: 'Кальцінований захищений жир',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 23,
    name: 'Propylenglycol',
    manufacturer: 'VILOFOSS',
    description: 'Енергетична рідка добавка',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 24,
    name: 'Glycerine 80%',
    manufacturer: 'VILOFOSS',
    description: 'Енергетична рідка добавка',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 25,
    name: 'VitaloMix',
    manufacturer: 'VILOFOSS',
    description: 'Престартер у вигляді мюсли',
    category: ['ВРХ молодняк'],
    image: imgProductDetails1,
  },
  {
    id: 26,
    name: 'Ruminito TMR',
    manufacturer: 'VILOFOSS',
    description: '10% ядро для кормів телятам',
    category: ['ВРХ молодняк'],
    image: imgProductDetails1,
  },
  {
    id: 27,
    name: 'Vollmilch plus',
    manufacturer: 'VILOFOSS',
    description: 'Збагачувач незбираного молока',
    category: ['ВРХ молодняк'],
    image: imgProductDetails1,
  },
  {
    id: 28,
    name: 'Євролак (зелений)',
    manufacturer: 'Schils',
    description: 'ЗНМ для телят з 3-ї доби життя',
    category: ['ВРХ молодняк'],
    image: imgProductDetails1,
  },
  {
    id: 29,
    name: 'RoCoSal E',
    manufacturer: 'VILOFOSS',
    description: 'Профілактика діареї у телят',
    category: ['ВРХ молодняк'],
    image: imgProductDetails1,
  },
  {
    id: 30,
    name: 'Dialyt Express',
    manufacturer: 'VILOFOSS',
    description: 'Швидке лікування діареї у телят',
    category: ['ВРХ молодняк', 'ДРХ', 'Коні'],
    image: imgProductDetails1,
  },
  {
    id: 31,
    name: 'RespoSan',
    manufacturer: 'VILOFOSS',
    description: 'Профілактика респіраторних хвороб у телят',
    category: ['ВРХ молодняк'],
    image: imgProductDetails1,
  },
  {
    id: 32,
    name: 'ProbioBona',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Рідкий пероральний пробіотик в шприці',
    category: ['Підходе для всіх'],
    image: imgProductDetails1,
  },
  {
    id: 33,
    name: 'Marathon Top',
    manufacturer: 'VILOFOSS',
    description: 'Спеціальний Премікс',
    category: ['ВРХ дорослі', 'ВРХ молодняк'],
    image: imgProductDetails1,
  },
  {
    id: 34,
    name: 'Stalosan F',
    manufacturer: 'VILOFOSS',
    description: 'Дезинфектант в присутності тварин',
    category: ['Підходе для всіх'],
    image: imgProductDetails1,
  },
  {
    id: 35,
    name: 'БІО-СИЛ',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Інокулянт для силосування',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 36,
    name: 'Sweet-Min Schafe',
    manufacturer: 'VILOFOSS',
    description: 'Лизунець меласований для овець',
    category: ['ДРХ'],
    image: imgProductDetails1,
  },
  {
    id: 37,
    name: 'FUTTERGUT™',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Кормові концентрати та премікси для свиней, птиці, ВРХ',
    category: ['Підходе для всіх'],
    image: imgProductDetails1,
  },
  {
    id: 38,
    name: 'Престартер для телят',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Престартер для телят. Гранула.',
    category: ['ВРХ молодняк'],
    image: imgProductDetails1,
  },
  {
    id: 39,
    name: 'БМВД (універсальний)',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'БМВД. Гранула.',
    category: ['ВРХ дорослі', 'ВРХ молодняк', 'ДРХ', 'Коні'],
    image: imgProductDetails1,
  },
  {
    id: 40,
    name: 'БМВД для корів',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Для лактуючих корів.',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 41,
    name: 'Гранула для корів',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Годівля на роботах',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 42,
    name: 'Премікс для дійних корів 1%',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Премікс з/без живими дріжджами',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 43,
    name: 'Футтергут-Лєвуселл для ВРХ',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Добавка з живими дріжджами',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 44,
    name: 'Премікс для дійних корів 3%',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Вітаміно-мінеральний Премікс',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 45,
    name: 'Премікс для сухостійних корів',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Премікс для сухостійних корів',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 46,
    name: 'AnkonaF/buffer/150',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Буферна добавка',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 47,
    name: 'Futtergut Hy-М',
    manufacturer: 'FUTTERGUT - надійна годівля',
    description: 'Регулює кальцій-фосфорний метаболізм + іммунітет',
    category: ['Свині'],
    image: imgProductDetails1,
  },
  {
    id: 48,
    name: 'NutriBos N 85 і NutriBos N 65',
    manufacturer: 'NUTRIBOS',
    description: 'Захищена сечовина (Хорватія)',
    category: ['ВРХ дорослі', 'ДРХ'],
    image: imgProductDetails1,
  },
  {
    id: 49,
    name: 'NutriBos VN 75 і COMPLETE',
    manufacturer: 'NUTRIBOS',
    description:
      'Комплексні продукти с захищеною сечовиною у складі (Хорватія)',
    category: ['ВРХ дорослі'],
    image: imgProductDetails1,
  },
  {
    id: 50,
    name: 'SEGAWEAN® Boost',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Премікс для свиней на відгодівлі 30-60 кг, 4,5%',
    category: ['Свині'],
    image: imgProductDetails1,
  },
  {
    id: 51,
    name: 'SEGAWEAN® F49 A3',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Премікс для свиней на відгодівлі від 60 кг, 3,3%',
    category: ['Свині'],
    image: imgProductDetails1,
  },
  {
    id: 52,
    name: 'SOW Day 7® Farrow Feed',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Премікс для свиноматок у транзитний період',
    category: ['Свині'],
    image: imgProductDetails1,
  },
  {
    id: 53,
    name: 'SEGAWEAN® SL Wean',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Премікс для лактуючих свиноматок, 5%',
    category: ['Свині'],
    image: imgProductDetails1,
  },
  {
    id: 54,
    name: 'SEGAWEAN® SFT',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Премікс для супоросних свиноматок, 3%',
    category: ['Свині'],
    image: imgProductDetails1,
  },
  {
    id: 55,
    name: 'SEGAWEAN® P5 +2 3 6',
    manufacturer: 'Ahrhoff FUTTERGUT',
    description: 'Премікс для поросят до 30 кг 6,5%',
    category: ['Свині'],
    image: imgProductDetails1,
  },
  {
    id: 56,
    name: 'Maxi-Cox Dry для птиці',
    manufacturer: 'ETOS',
    description:
      'Модулятор мікробіому; Кокцидіостатик; Суміш органічних кислот',
    category: ['Птиця'],
    image: imgProductDetails1,
  },
  {
    id: 57,
    name: 'Maxi-Pi-Blok Dry - для свиней',
    manufacturer: 'ETOS',
    description:
      'Модулятор мікробіому; Альтернатива антибіотику; Суміш органічних кислот',
    category: ['Свині'],
    image: imgProductDetails1,
  },
  {
    id: 58,
    name: 'Hy-M для свиней',
    manufacturer: ['ANKONA', 'FUTTERGUT - надійна годівля'],
    description:
      'Модулятор мікробіому; Альтернатива антибіотику; Суміш органічних кислот',
    category: ['Свині'],
    image: imgProductDetails1,
  },
  {
    id: 59,
    name: 'Hy-M для батьківського стада птиці',
    manufacturer: ['ANKONA', 'FUTTERGUT - надійна годівля'],
    description: 'Підвищення рівня вітаміну D3 у сироватці крові',
    category: ['Птиця'],
    image: imgProductDetails1,
  },
  {
    id: 60,
    name: 'Hy-M для бройлерів',
    manufacturer: ['ANKONA', 'FUTTERGUT - надійна годівля'],
    description: 'Підвищення рівня вітаміну D3 у сироватці крові',
    category: ['Птиця'],
    image: imgProductDetails1,
  },
  {
    id: 61,
    name: 'Hy-M для несучки',
    manufacturer: ['ANKONA', 'FUTTERGUT - надійна годівля'],
    description: 'Підвищення рівня вітаміну D3 у сироватці крові',
    category: ['Птиця'],
    image: imgProductDetails1,
  },
  {
    id: 62,
    name: 'Мультіцид Форте',
    manufacturer: ['ETOS'],
    description: 'Додаткова кормова суміш',
    category: ['Підходе для всіх'],
    image: imgProductDetails1,
  },
  {
    id: 63,
    name: 'Цітро',
    manufacturer: ['Agro-Bizek'],
    description: 'Ультрабіотик',
    category: ['Підходе для всіх'],
    image: imgProductDetails1,
  },
  {
    id: 64,
    name: 'Арбоцель',
    manufacturer: ['JRS'],
    description: 'Концентрат сирої клітковини для свиней',
    category: ['Свині'],
    image: imgProductDetails1,
  },
];

export function addNewEvent(newEvent) {
  products.push(newEvent);
}
